Add linewidth parameter
sepandhaghighi/samila pull request #106
Opened 2022-03-22 01:51 UTC by evanofslack

#### Reference Issues/PRs
#101

#### What does this implement/fix? Explain your changes.
Implements the linewidth parameter. Includes updates to the `plot` method,  `plot_params_filter` function as well as the various `load` and `save` functions.

2022-03-22 06:40 UTC, sadrasabouri approved these changes
Good job!
I think it's OK.
@sepandhaghighi please take a look at it.

2022-03-22 11:37 UTC, sepandhaghighi requested changes
@evanofslack Thanks for your effort 💯 
Please take a look at my comments (minor issues)

2022-03-22 11:37 UTC, sepandhaghighi commented on CHANGELOG.md
>  ## [Unreleased]
Please add `### Changed` here

2022-03-22 11:37 UTC, sepandhaghighi commented on samila/params.py
> +DEFAULT_LINEWIDTH = 1.0
`1.0` or  `1.5`?

Reference: [https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter)

2022-03-22 23:53 UTC, evanofslack commented on CHANGELOG.md
>  ## [Unreleased]
Done!

2022-03-25 12:53 UTC, sepandhaghighi approved these changes
LGTM 🚀

2022-03-25 12:55 UTC, merged