Link and Path fields added
sepandhaghighi/samila pull request #109
Opened 2022-04-04 13:17 UTC by sadrasabouri

#### Reference Issues/PRs
#99 
#### What does this implement/fix? Explain your changes.
Since we need to know what's the link of uploaded art in the nft storage we decided to return the link to the art in the when using `nft_storage_upload` method.
Same issue when saving a config/data/art file.

2022-04-04 22:28 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 
JSON field shouldn't be dynamic (sometimes `message` sometimes `link`/`path`)
I suggest replacing `link` and `path` with `message`

2022-04-05 06:01 UTC, sadrasabouri commented
> 

I think message field is necessary in some cases in which we return error message in `message` field and these error messages can not be in the `link`/`path` field.

2022-04-05 08:09 UTC, sepandhaghighi requested changes

2022-04-05 08:09 UTC, sepandhaghighi commented on samila/params.py
> +NFT_STORAGE_LINK = "https://{}.ipfs.nftstorage.link/"
I suggest this format:
`https://ipfs.io/ipfs/{}`

2022-04-05 08:09 UTC, sepandhaghighi commented on samila/functions.py
> +        result["message"] = os.path.dirname(os.path.abspath(file_adr))
I think a direct file address (`os.path.abspath(file_adr)`) is better than a folder address. isn't?

2022-04-06 11:01 UTC, sepandhaghighi approved these changes
LGTM 🚀

2022-04-06 11:06 UTC, merged