Transparent Feature Added
sepandhaghighi/samila pull request #133
Opened 2022-05-17 20:27 UTC by sadrasabouri

#### Reference Issues/PRs
#118 

#### What does this implement/fix? Explain your changes.
+ transparent background added
+ `set_background` function added

2022-05-18 06:33 UTC, sepandhaghighi requested changes

2022-05-18 06:33 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `transparent` bgcolor
Move this line to `### Changed` section, something like:
- Transparent mode support for `bgcolor` parameter

2022-05-18 07:08 UTC, sepandhaghighi requested changes

2022-05-18 07:08 UTC, sepandhaghighi commented on samila/functions.py
> +    :type ax: matplotlib.pyplot.figure
Is it correct?

2022-05-18 07:08 UTC, sepandhaghighi commented on README.md
Please update here with this sentence:

⚠️ **Transparent** mode is only available for background

2022-05-18 07:08 UTC, sepandhaghighi commented on examples/demo.ipynb
>     ]
Please update here with this sentence:

⚠️ **Transparent** mode is only available for background

2022-05-18 08:22 UTC, sadrasabouri commented on samila/functions.py
> +    :type ax: matplotlib.pyplot.figure
Solved in new commit.

2022-05-19 21:49 UTC, sepandhaghighi approved these changes
LGTM 🚀

2022-05-19 21:49 UTC, merged