Data/Config Upload to IPFS
sepandhaghighi/samila pull request #164
Opened 2022-11-14 10:45 UTC by sadrasabouri

#### Reference Issues/PRs
#145  and #144 

#### What does this implement/fix? Explain your changes.
##### Added
- `get_data` function
- `get_config` function
##### Changed
- `upload_data` parameter added to `nft_storage` method
- `upload_config` parameter added to `nft_storage` method

#### Any other comments?

2022-11-17 00:10 UTC, sepandhaghighi requested changes

2022-11-17 00:10 UTC, sepandhaghighi commented on README.md
> +
Please add an example for `upload_data` mode

2022-11-17 00:10 UTC, sepandhaghighi commented on examples/demo.ipynb
> +    "g.nft_storage(api_key=\"YOUR_API_KEY\", upload_config=True)"
`g1` instead of `g`

2022-11-17 00:10 UTC, sepandhaghighi commented on examples/demo.ipynb
> +   ]
Please add an example for `upload_data` mode

2022-11-17 07:18 UTC, sadrasabouri commented
@sepandhaghighi can you please review it again? I fixed the problems.

2022-11-17 20:06 UTC, sepandhaghighi requested changes

2022-11-17 20:06 UTC, sepandhaghighi commented on test/nft_upload_test.py
> +>>> while(status == False and counter<try_limit):
To increase coverage, I suggest splitting this test:

```pycon
>>> status = False
>>> counter = 0
>>> while(status == False and counter<try_limit):
...     result = g.nft_storage(api_key=NFT_STORAGE_API_KEY, upload_data=True, depth=1)
...     counter = counter + 1
...     status = result["status"]
...     time.sleep(10)
>>> status["image"]
True
>>> status["data"]
True
>>> status = False
>>> counter = 0
>>> while(status == False and counter<try_limit):
...     result = g.nft_storage(api_key=NFT_STORAGE_API_KEY, upload_config=True, depth=1)
...     counter = counter + 1
...     status = result["status"]
...     time.sleep(10)
>>> status["image"]
True
>>> status["config"]
True
```

2022-11-18 07:37 UTC, sadrasabouri commented
@sepandhaghighi I believe now it's ready. :rocket:

2022-11-22 09:31 UTC, sepandhaghighi approved these changes
LGTM 🚀

2022-11-22 09:31 UTC, merged