Cli
sepandhaghighi/samila pull request #233
Opened 2024-09-29 21:50 UTC by sadrasabouri

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
Command Line Interface (CLI) added.

#### Any other comments?

2024-09-30 15:17 UTC, sepandhaghighi requested changes
@sadrasabouri Thanks for your efforts 💯 
Please review my comments and remember to update `README.md` as well.

2024-09-30 15:17 UTC, sepandhaghighi commented on samila/__main__.py
> +    if args.version:
`--version` flag should only return version number.
```shell
> samila --version
1.3
```

Add another flag like `--info` for this purpose.

2024-09-30 15:17 UTC, sepandhaghighi commented on samila/__main__.py
> +        plt.show()
Add a flag like `--show-image` to control this option.
Default: `True`

2024-09-30 22:37 UTC, sadrasabouri commented
@sepandhaghighi would you please re-review this?
Also, I don't know why CLI takes so long on Windows to run.
Can you check that manually?

2024-10-02 01:26 UTC, sadrasabouri commented
@sepandhaghighi I fixed the windows issue by adding the flag `--no-display`. Re-review it once you get a chance.

2024-10-13 15:56 UTC, sepandhaghighi approved these changes
🔥

2024-10-13 15:56 UTC, merged