Complex data
sepandhaghighi/samila pull request #67
Opened 2021-10-29 15:08 UTC by sadrasabouri

#### Reference Issues/PRs
#64 

#### What does this implement/fix? Explain your changes.
Casting both `data1` and `data2` into real part solved the complex data saving issue.

2021-10-29 21:28 UTC, sepandhaghighi requested changes

2021-10-29 21:28 UTC, sepandhaghighi commented on samila/genimage.py
> +        self.data1 = list(map(lambda x: x.real, self.data1))
This implementation is correct but it's not efficient.
It's better to filter the imaginary part in the previous loop (before appending)

2021-10-29 21:28 UTC, sepandhaghighi commented on test/overall_test.py
> +>>> g.generate(seed=755398)
Please add some tests here, to check that `data1` and `data2` does not include any complex numbers

2021-10-30 06:35 UTC, sadrasabouri commented
@sepandhaghighi Please review again.

2021-10-30 09:24 UTC, sepandhaghighi approved these changes

2021-10-30 09:24 UTC, merged